# Tests for paper_analysis/none_showcase.py
# This script looks only at the 32 "None of the above"-correct questions and
# compares three ways of scoring GPT-4o on them: the benchmark's own faithful
# pipeline, a perfect letter parser on the same replies, and a coax-prompt reply
# scored by the same parser. It writes a table + a values.json.

import os
import json

import pandas as pd

import none_showcase as ns


def _write_fixture(tmp_path):
    # 4 of the real 32 "None"-correct indices (none_showcase.BLANK_CORRECT), so
    # the filter in main() keeps them.
    idx = [41, 50, 58, 73]
    opts = pd.DataFrame({
        "index": idx,
        "option1": ["None"] * 4,
        "option2": ["Foo"] * 4,
        "option3": ["Bar"] * 4,
        "option4": ["Baz"] * 4,
    })
    opts_path = tmp_path / "data" / "closed_ended.parquet"
    opts_path.parent.mkdir(parents=True)
    opts.to_parquet(opts_path)

    # faithful replies: 41 and 58 are clean bare letters; 50 is a verbose reply
    # where the benchmark's own parser latches onto the FIRST mentioned letter
    # (B, from "Options B and C are wrong") instead of the letter the model
    # actually settles on at the end (A) -- extract_letter reads the real answer,
    # the benchmark parser does not; 73 is answered via the option TEXT ("None")
    # rather than a letter, which the benchmark's text-matching parser catches
    # but the letter-only extract_letter does not.
    fa = pd.DataFrame({
        "index": idx,
        "raw_response": [
            "(A)",
            "Options B and C are wrong. The correct answer is A.",
            "B",
            "I think the correct choice is None.",
        ],
        "answer": ["A", "A", "B", "A"],
    })
    cx = pd.DataFrame({
        "index": idx,
        "raw_response": ["A", "A", "B", "A"],
        "answer": ["A", "A", "B", "A"],
    })
    faithful_path = tmp_path.joinpath(*ns.FAITHFUL.split("/"))
    coax_path = tmp_path.joinpath(*ns.COAX.split("/"))
    faithful_path.parent.mkdir(parents=True, exist_ok=True)
    coax_path.parent.mkdir(parents=True, exist_ok=True)
    fa.to_csv(faithful_path, index=False)
    cx.to_csv(coax_path, index=False)


def test_main_computes_and_writes_the_three_accuracies(tmp_path, monkeypatch, capsys):
    _write_fixture(tmp_path)
    out_dir = tmp_path / "_generated"
    monkeypatch.setattr(ns, "REPO", str(tmp_path))
    monkeypatch.setattr(ns, "OUT_DIR", str(out_dir))

    ns.main()
    out = capsys.readouterr().out

    # bench: 41 right, 50 wrong (parser reads "B" first), 58 right, 73 right = 3/4
    # true:  41 right, 50 right (extract_letter reads the real "A"), 58 right,
    #        73 wrong (extract_letter doesn't do option-text matching) = 3/4
    # coax:  all 4 bare-letter replies match = 4/4
    assert 'GPT-4o on the 4 "none of the above" questions' in out
    assert "Benchmark pipeline (its prompt, its parser) | 75.0% |" in out
    assert "Its prompt, but scored by the model's real answer | 75.0% |" in out
    assert "Coax prompt (bare letter, benchmark parser) | 100.0% |" in out
    assert "parser effect +0.0, prompt effect +25.0, total +25.0 (on 4 items)" in out

    table_path = out_dir / "none_showcase_table.md"
    values_path = out_dir / "none_showcase.values.json"
    assert table_path.exists()
    assert values_path.exists()

    vals = json.loads(values_path.read_text(encoding="utf-8"))
    assert vals["n"] == 4
    assert vals["benchmark_pipeline_pct"] == 75.0
    assert vals["perfect_parser_pct"] == 75.0
    assert vals["coax_pct"] == 100.0
    assert vals["parser_effect_pts"] == 0.0
    assert vals["prompt_effect_pts"] == 25.0
    assert vals["total_pts"] == 25.0
    assert vals["_generator"] == "paper_analysis/none_showcase.py"
    assert vals["_source_csv"] == [ns.FAITHFUL, ns.COAX]

    table_text = table_path.read_text(encoding="utf-8")
    assert table_text.startswith("<!-- GENERATED by paper_analysis/none_showcase.py")
    assert "Benchmark pipeline" in table_text
