"""
GENERATOR for: PAPER_DRAFT.md  §5.1  "What the blanks cost a real model" (table + stats)

Produces, from the committed raw-output CSV of the E0-repro GPT-4o run, the
whole / clean / blank-item accuracy table and the answerable-vs-unanswerable
two-proportion z-test. No API calls: pure re-score of raw model outputs, so every
number is regenerable.

Run:   python paper_analysis/blank_split.py
Reads: results/closed_ended/reproduction/gpt-4o-2024-11-20__faithful-direct-k0__whole__n491.csv
Writes (committed, do not hand-edit):
  paper_analysis/_generated/blank_split_table.md      -> the Markdown table for §5.1
  paper_analysis/_generated/blank_split.values.json   -> the scalars (acc, CI, z, p) + provenance

Blank-item indices are the source-data artifact verified three ways in RESEARCH_PLAN §3.7.
"""
import os
import json
import math
import datetime
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
# repo-relative, forward-slash (portable + clean provenance strings)
SOURCE_CSV = ("results/closed_ended/reproduction/"
              "gpt-4o-2024-11-20__faithful-direct-k0__whole__n491.csv")
OUT_DIR = os.path.join(HERE, "_generated")

BLANK_CORRECT = {41, 50, 58, 73, 77, 87, 91, 105, 113, 114, 116, 125, 175, 188, 199,
                 205, 230, 240, 288, 297, 327, 337, 391, 396, 435, 440, 444, 446, 455,
                 456, 477, 486}
BLANK_DISTRACTOR = {45, 48, 162, 204, 243, 325}
BLANK_OPTION = BLANK_CORRECT | BLANK_DISTRACTOR


def wilson(k, n, z=1.96):
    p = k / n
    den = 1 + z * z / n
    c = (p + z * z / (2 * n)) / den
    h = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / den
    return round(100 * (c - h), 1), round(100 * (c + h), 1)


def two_prop_z(k1, n1, k2, n2):
    p1, p2 = k1 / n1, k2 / n2
    pooled = (k1 + k2) / (n1 + n2)
    se = math.sqrt(pooled * (1 - pooled) * (1 / n1 + 1 / n2))
    z = (p1 - p2) / se
    p = math.erfc(abs(z) / math.sqrt(2))  # two-sided normal tail
    return round(z, 2), p


def main():
    csv_abs = os.path.join(REPO, *SOURCE_CSV.split("/"))
    d = pd.read_csv(csv_abs)
    sets = {
        "whole": d,
        "clean": d[~d["index"].isin(BLANK_OPTION)],
        "blank": d[d["index"].isin(BLANK_CORRECT)],
    }
    vals = {}
    for name, sub in sets.items():
        k, n = int(sub["correct"].sum()), len(sub)
        lo, hi = wilson(k, n)
        vals[name] = {"n": n, "k": k, "acc": round(100 * k / n, 1), "ci": [lo, hi]}

    z, p = two_prop_z(vals["clean"]["k"], vals["clean"]["n"],
                      vals["blank"]["k"], vals["blank"]["n"])
    vals["clean_vs_blank_z"] = z
    vals["clean_vs_blank_p"] = p

    os.makedirs(OUT_DIR, exist_ok=True)
    stamp = datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")
    prov = (f"<!-- GENERATED by paper_analysis/blank_split.py from {SOURCE_CSV} "
            f"on {stamp}. Do not hand-edit; run `python paper_analysis/blank_split.py`. -->")

    def row(label, s):
        lo, hi = s["ci"]
        return f"| {label} | {s['n']} | {s['acc']}% | {lo} to {hi} |"

    table = "\n".join([
        prov,
        "| Questions | Count | GPT-4o accuracy | 95% Wilson range |",
        "|---|---:|---:|:--|",
        row("Complete set (as released)", vals["whole"]),
        row("Clean set (answerable only)", vals["clean"]),
        row("Blank items (unanswerable)", vals["blank"]),
        "",
    ])
    with open(os.path.join(OUT_DIR, "blank_split_table.md"), "w", encoding="utf-8") as f:
        f.write(table)

    vals["_generator"] = "paper_analysis/blank_split.py"
    vals["_source_csv"] = SOURCE_CSV
    vals["_generated_utc"] = stamp
    with open(os.path.join(OUT_DIR, "blank_split.values.json"), "w", encoding="utf-8") as f:
        json.dump(vals, f, indent=2)

    print(table)
    print(f"clean vs blank (two-proportion z): {vals['clean']['acc']}% vs "
          f"{vals['blank']['acc']}%, z = {z}, p = {p:.2e}")
    print(f"\nwrote {OUT_DIR}/blank_split_table.md and blank_split.values.json")


if __name__ == "__main__":
    main()
