"""
GENERATOR for: PAPER_DRAFT.md §5.3.4 — effective scores on the position-balanced set.

Reports each model on the shuffled (balanced) key along TWO orthogonal axes, both computed
from the paired original+shuffled runs (all on the frozen 491, revised/coax prompt, direct,
temperature 0, identical settings):

  * position-robust accuracy = fraction of questions the model answers correctly under BOTH the
    original and the shuffled option order. This is a two-order instance of MMBench's
    CircularEval (arXiv:2307.06281); it is a real accuracy (§5.3.4 headline / effective score).
  * letter-bias index = how far the model's predicted-letter distribution on the shuffled key
    sits from a balanced 25/25/25/25 spread, normalized to 0-100% (0 = uniform, 100 = always one
    letter). Measured on the shuffled key so that uniform is the honest target and the number is
    not contaminated by the original key's own skew. chi-square (df=3, p<.05 at 7.82) marks
    whether the imbalance is beyond chance.

The two axes are independent: a model can be letter-unbiased yet unstable (content churn) or
letter-biased yet stable. Reported together they say whether a headline accuracy is real.

Run:   python paper_analysis/effective_score.py
Reads (all committed, no API): the six paired 491 run CSVs below.
Writes: paper_analysis/_generated/effective_score_table.md + .values.json
"""
import os
import sys
import json
import math
import datetime
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
OUT_DIR = os.path.join(HERE, "_generated")
try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

CE = "results/closed_ended"
PB = f"{CE}/position_bias"
MODELS = [
    ("GPT-4o", f"{CE}/gpt-4o-2024-11-20__coax-direct-k0__whole__n491.csv",
              f"{PB}/gpt-4o-2024-11-20__coax-direct-k0__shuffled__n491.csv"),
    ("Gemini-2.5-flash", f"{PB}/gemini-2.5-flash__coax-direct-k0__whole__n491.csv",
                         f"{PB}/gemini-2.5-flash__coax-direct-k0__shuffled__n491.csv"),
    ("Gemini-3.5-flash", f"{PB}/gemini-3.5-flash__coax-direct-k0__whole__n491.csv",
                         f"{PB}/gemini-3.5-flash__coax-direct-k0__shuffled__n491.csv"),
]
LETTERS = list("ABCD")


def wilson(k, n, z=1.96):
    p = k / n
    d = 1 + z * z / n
    c = (p + z * z / (2 * n)) / d
    h = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d
    return round(100 * (c - h), 1), round(100 * (c + h), 1)


def letter_bias(df):
    """Normalized distance of predictions from uniform, on this run. 0=uniform, 1=one letter.
    Also returns the chi-square goodness-of-fit vs uniform (df=3)."""
    counts = df["predicted"].value_counts().reindex(LETTERS).fillna(0)
    n = int(counts.sum())
    p = counts / n
    raw = 0.5 * (p - 0.25).abs().sum()          # total-variation distance from uniform
    index = raw / 0.75                            # 0.75 = max (a point mass), so index in [0,1]
    exp = n / 4
    chi2 = float(((counts - exp) ** 2 / exp).sum())
    return round(index * 100, 0), round(chi2, 1)


def main():
    rows, vals = [], {}
    for name, op, sp in MODELS:
        o = pd.read_csv(os.path.join(REPO, *op.split("/"))).set_index("index")
        s = pd.read_csv(os.path.join(REPO, *sp.split("/"))).set_index("index")
        common = o.index.intersection(s.index)
        o, s = o.loc[common], s.loc[common]
        n = len(common)
        ao = round(100 * o["correct"].mean(), 1)
        as_ = round(100 * s["correct"].mean(), 1)
        both = o["correct"].values & s["correct"].values
        pr = round(100 * both.mean(), 1)
        prlo, prhi = wilson(int(both.sum()), n)
        bias, chi2 = letter_bias(s)               # bias measured on the shuffled key
        sig = "\\*" if chi2 > 7.82 else ""
        rows.append((name, ao, as_, round(ao - as_, 1), pr, (prlo, prhi), int(bias), chi2, sig))
        vals[name] = {"n": n, "acc_original": ao, "acc_shuffled": as_, "drop": round(ao - as_, 1),
                      "position_robust_acc": pr, "position_robust_ci": [prlo, prhi],
                      "letter_bias_index": int(bias), "chi2_vs_uniform": chi2,
                      "letter_bias_significant": chi2 > 7.82}

    vals["_generator"] = "paper_analysis/effective_score.py"
    vals["_source_csv"] = [c for _, o, s in MODELS for c in (o, s)]
    vals["_generated_utc"] = datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")

    os.makedirs(OUT_DIR, exist_ok=True)
    prov = (f"<!-- GENERATED by paper_analysis/effective_score.py on {vals['_generated_utc']}. "
            f"Do not hand-edit; run `python paper_analysis/effective_score.py`. -->")
    table = [prov,
             "| Model (491 questions) | Orig key | Shuffled key | Drop | Position-robust acc [95% CI] | Letter-bias index |",
             "|:--|--:|--:|--:|--:|--:|"]
    for name, ao, as_, drop, pr, (lo, hi), bias, chi2, sig in rows:
        table.append(f"| {name} | {ao}% | {as_}% | {drop} | {pr}% [{lo}–{hi}] | {bias}%{sig} |")
    table.append("")
    table = "\n".join(table)

    with open(os.path.join(OUT_DIR, "effective_score_table.md"), "w", encoding="utf-8") as f:
        f.write(table)
    with open(os.path.join(OUT_DIR, "effective_score.values.json"), "w", encoding="utf-8") as f:
        json.dump(vals, f, indent=2)

    print(table)
    print("\n\\* = letter distribution significantly non-uniform (chi-square > 7.82, df=3, p<.05)")
    for name, *_ , chi2, sig in rows:
        pass
    print("chi-square vs uniform (shuffled key):", {r[0]: r[7] for r in rows})


if __name__ == "__main__":
    main()
