"""
READOUT for the ensemble / deliberation probe (**NEGATIVE**; not yet a paper element).

Answers three questions about `eval_open/run_ensemble.py`'s output, with no API calls:
  1. How far is the per-item ORACLE above each single model? (the headroom deliberation
     would have to capture)
  2. Where did the ensemble actually land, paired against the gemini baseline?
  3. What did the model DO — keep its own draft, defer to the other model's, or rewrite?

Result: the ensemble lands far BELOW both drafts. Deliberation as run here is a dead end.
Caveat carried in the output: the ensemble arm is not prompt-matched to the baseline (no
OPG primer, one call per question rather than per image, and a "reply with ONLY your single
best final answer" instruction), so the drop mixes deliberation together with a terser
prompt. It bounds the arm, it does not isolate deliberation.

Run:   python -m paper_analysis.ensemble_delta
Reads: data/open_ended.parquet,
       results/open/batched_gemini35_plain578_scores.csv  (+ answers, for the behaviour split)
       results/open/batched_gpt5mini_scores.csv           (+ answers)
       results/open/ensemble_gemjudge_concrete_{answers,scores}.csv
Writes: paper_analysis/_generated/ensemble_delta_table.md
        paper_analysis/_generated/ensemble_delta.values.json
"""
import datetime
import json
import os
import re
from math import sqrt

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
OUT_DIR = os.path.join(HERE, "_generated")


def p(*rel):
    return os.path.join(REPO, *rel)


def norm(t):
    """Loose text key for 'is this the same answer' — punctuation-insensitive, first 200 chars."""
    return re.sub(r"\W+", " ", str(t)).strip().lower()[:200]


def ci95(d):
    se = d.std(ddof=1) / sqrt(len(d))
    return round(d.mean() * 100, 1), round((d.mean() - 1.96 * se) * 100, 1), round((d.mean() + 1.96 * se) * 100, 1)


def main():
    data = pd.read_parquet(p("data/open_ended.parquet"))[["index", "question", "answer"]]
    gem = pd.read_csv(p("results/open/batched_gemini35_plain578_scores.csv")).rename(columns={"score": "gem"})
    gpt = pd.read_csv(p("results/open/batched_gpt5mini_scores.csv")).rename(columns={"score": "gpt"})
    ens = pd.read_csv(p("results/open/ensemble_gemjudge_concrete_scores.csv")).rename(columns={"score": "ens"})
    gem_a = pd.read_csv(p("results/open/batched_gemini35_plain578_answers.csv")).set_index("index")["answer"]
    gpt_a = pd.read_csv(p("results/open/batched_gpt5mini_answers.csv")).set_index("index")["answer"]
    ens_a = pd.read_csv(p("results/open/ensemble_gemjudge_concrete_answers.csv")).set_index("index")

    m = data.merge(gem, on="index").merge(gpt, on="index").merge(ens, on="index")
    n = len(m)
    oracle = m[["gem", "gpt"]].max(axis=1)
    d = m.ens - m.gem
    delta, lo, hi = ci95(d)
    gap = oracle.mean() - m.gem.mean()

    vals = {
        "n": n,
        "gemini35_baseline": round(m.gem.mean() * 100, 1),
        "gpt5mini": round(m.gpt.mean() * 100, 1),
        "per_item_oracle": round(oracle.mean() * 100, 1),
        "ensemble": round(m.ens.mean() * 100, 1),
        "delta_vs_gemini": [delta, lo, hi],
        "oracle_gap_pts": round(gap * 100, 1),
        "captured_of_oracle_gap_pct": round((m.ens.mean() - m.gem.mean()) / gap * 100, 1) if gap else None,
        "items_beat_both_drafts": int((m.ens > oracle).sum()),
        "items_worse_than_both_drafts": int((m.ens < m[["gem", "gpt"]].min(axis=1)).sum()),
    }

    # behaviour: did the model keep its own draft, take the other one, or write a new answer?
    same_gem = same_gpt = revised = 0
    for idx in ens_a.index:
        f = norm(ens_a.loc[idx, "final"])
        if f == norm(gem_a.get(idx, "")):
            same_gem += 1
        elif f == norm(gpt_a.get(idx, "")):
            same_gpt += 1
        else:
            revised += 1
    vals["behaviour"] = {"kept_own_draft": same_gem, "took_other_draft": same_gpt, "rewrote": revised}
    vals["caveat"] = ("Not prompt-matched to the baseline: the ensemble arm drops the OPG primer, "
                      "calls once per question instead of once per image, and asks for a single terse "
                      "final answer. Bounds this arm; does not isolate deliberation.")

    os.makedirs(OUT_DIR, exist_ok=True)
    stamp = datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")
    rows = [
        f"<!-- GENERATED by paper_analysis/ensemble_delta.py on {stamp}. "
        f"Do not hand-edit; run `python -m paper_analysis.ensemble_delta`. -->",
        f"| System (concrete questions, n={n}) | score |",
        "|:--|--:|",
        f"| gemini-3.5-flash (baseline draft) | {vals['gemini35_baseline']}% |",
        f"| gpt-5-mini (second draft) | {vals['gpt5mini']}% |",
        f"| per-item oracle (better of the two) | {vals['per_item_oracle']}% |",
        f"| **ensemble** (gemini re-reads with both drafts) | **{vals['ensemble']}%** |",
    ]
    table = "\n".join(rows) + "\n"
    with open(os.path.join(OUT_DIR, "ensemble_delta_table.md"), "w", encoding="utf-8") as f:
        f.write(table)
    vals["_generator"] = "paper_analysis/ensemble_delta.py"
    vals["_source_csv"] = ["results/open/ensemble_gemjudge_concrete_scores.csv",
                           "results/open/batched_gemini35_plain578_scores.csv",
                           "results/open/batched_gpt5mini_scores.csv"]
    vals["_generated_utc"] = stamp
    with open(os.path.join(OUT_DIR, "ensemble_delta.values.json"), "w", encoding="utf-8") as f:
        json.dump(vals, f, indent=2)

    print(table)
    print(f"delta vs gemini baseline: {delta:+.1f} pts  [{lo:+.1f}, {hi:+.1f}]")
    print(f"oracle headroom was {vals['oracle_gap_pts']:+.1f} pts; captured {vals['captured_of_oracle_gap_pct']}%")
    print(f"beat BOTH drafts: {vals['items_beat_both_drafts']}   worse than BOTH: {vals['items_worse_than_both_drafts']}")
    b = vals["behaviour"]
    print(f"behaviour: kept own {b['kept_own_draft']} | took other {b['took_other_draft']} | rewrote {b['rewrote']}")
    print(f"\nCAVEAT: {vals['caveat']}")
    print(f"wrote {OUT_DIR}/ensemble_delta_table.md and .values.json")


if __name__ == "__main__":
    main()
