"""
GENERATOR for: PAPER_DRAFT.md  §5.3.1  "The answer key leans toward one position"

The answer-key distribution across A/B/C/D. This is a property of the DATASET (the answer
key), not of any model, so it is derived from the released benchmark files rather than a
raw-output CSV. The clean set is the one the paper uses from §5.1 onward; the complete and
clean-shuffled sets are computed too, for the "removing blanks made it worse" point and for
the corrected version referenced in §5.3.4.

Run:   python paper_analysis/key_skew.py
Reads: data/closed_ended_clean.parquet, data/closed_ended.parquet,
       data/closed_ended_clean_shuffled.parquet   (regenerable via prepare_datasets.py)
Writes: paper_analysis/_generated/key_skew_table.md   (the §5.3.1 clean table)
        paper_analysis/_generated/key_skew.values.json
"""
import os
import json
import datetime
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
OUT_DIR = os.path.join(HERE, "_generated")
SETS = {
    "complete": "data/closed_ended.parquet",
    "clean": "data/closed_ended_clean.parquet",
    "clean_shuffled": "data/closed_ended_clean_shuffled.parquet",
}


def dist(path):
    d = pd.read_parquet(os.path.join(REPO, *path.split("/")))
    n = len(d)
    cnt = {L: int((d["answer"] == L).sum()) for L in "ABCD"}
    share = {L: round(100 * cnt[L] / n, 1) for L in "ABCD"}
    best = max(cnt, key=cnt.get)
    return {"n": n, "count": cnt, "share": share,
            "always_best_letter": best, "always_best_pct": share[best]}


def main():
    vals = {name: dist(path) for name, path in SETS.items()}
    c = vals["clean"]
    os.makedirs(OUT_DIR, exist_ok=True)
    stamp = datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")
    prov = (f"<!-- GENERATED by paper_analysis/key_skew.py on {stamp}. "
            f"Do not hand-edit; run `python paper_analysis/key_skew.py`. -->")
    rows = "\n".join(
        f"| {L} | {c['count'][L]} | {c['share'][L]}% |" for L in "ABCD")
    table = "\n".join([
        prov,
        f"| Correct-answer position | Questions (of {c['n']}) | Share of the key |",
        "|:--|--:|--:|",
        rows, "",
    ])
    with open(os.path.join(OUT_DIR, "key_skew_table.md"), "w", encoding="utf-8") as f:
        f.write(table)
    vals["_generator"] = "paper_analysis/key_skew.py"
    vals["_source"] = list(SETS.values())
    vals["_note"] = "dataset-derived (answer key), not model outputs"
    vals["_generated_utc"] = stamp
    with open(os.path.join(OUT_DIR, "key_skew.values.json"), "w", encoding="utf-8") as f:
        json.dump(vals, f, indent=2)

    print(table)
    print(f"clean:  always-{c['always_best_letter']} = {c['always_best_pct']}%  "
          f"(complete B = {vals['complete']['share']['B']}%, "
          f"clean-shuffled always-{vals['clean_shuffled']['always_best_letter']} = "
          f"{vals['clean_shuffled']['always_best_pct']}%)")
    print(f"\nwrote {OUT_DIR}/key_skew_table.md and key_skew.values.json")


if __name__ == "__main__":
    main()
