"""
GENERATOR for: PAPER_DRAFT.md §5.2 — the "none of the above" showcase.

On the 32 items whose correct answer is the "None" option, shows how the benchmark's own
pipeline turns a capable model into an apparent failure, and that fixing the READING and the
ASKING recovers it. All three numbers are re-derived from committed raw model outputs (no API):

  benchmark pipeline : faithful prompt, scored by the benchmark parser (faithful_predict with
                       the canonical "None" index2ans)                          ~= 25%
  perfect parser     : faithful prompt, scored by the model's real answer
                       (clients.parsing.extract_letter)                         ~= 28%
  coax prompt        : bare-letter answer, scored by the benchmark parser
                       (identical to a perfect parser on a bare letter)         ~= 53%

Run:   python paper_analysis/none_showcase.py
Reads: results/closed_ended/gpt-4o-...faithful...whole__n491.csv (canonical; filtered to the 32 "None")
       results/closed_ended/gpt-4o-...coax...whole__n491.csv (canonical)
       data/closed_ended.parquet   (canonical option text -> "None" index2ans)
Writes: paper_analysis/_generated/none_showcase_table.md + .values.json
"""
import os
import sys
import json
import datetime
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
OUT_DIR = os.path.join(HERE, "_generated")
sys.path.insert(0, REPO)
from clients.parsing import extract_letter          # noqa: E402
from utils.vlmeval_parse import faithful_predict     # noqa: E402

FAITHFUL = "results/closed_ended/gpt-4o-2024-11-20__faithful-direct-k0__whole__n491.csv"
COAX = "results/closed_ended/gpt-4o-2024-11-20__coax-direct-k0__whole__n491.csv"
# the 32 items whose correct answer is the "None" slot (RESEARCH_PLAN §3.7)
BLANK_CORRECT = {41, 50, 58, 73, 77, 87, 91, 105, 113, 114, 116, 125, 175, 188, 199, 205, 230,
                 240, 288, 297, 327, 337, 391, 396, 435, 440, 444, 446, 455, 456, 477, 486}


def main():
    opts = pd.read_parquet(os.path.join(REPO, "data/closed_ended.parquet")).set_index("index")
    fa = pd.read_csv(os.path.join(REPO, *FAITHFUL.split("/")))
    cx = pd.read_csv(os.path.join(REPO, *COAX.split("/")))
    fa = fa[fa["index"].isin(BLANK_CORRECT)]
    cx = cx[cx["index"].isin(BLANK_CORRECT)]
    n = len(fa)

    def idx2ans(i):
        return {L: str(opts.loc[i, f"option{k}"]) for L, k in zip("ABCD", [1, 2, 3, 4])}

    bench = sum(1 for _, r in fa.iterrows()
                if faithful_predict(str(r["raw_response"]), idx2ans(int(r["index"])),
                                    seed=int(r["index"]))[0] == r["answer"])
    true = sum(1 for _, r in fa.iterrows()
               if extract_letter(str(r["raw_response"])) == r["answer"])
    coax = sum(1 for _, r in cx.iterrows()
               if extract_letter(str(r["raw_response"])) == r["answer"])

    vals = {
        "n": n,
        "benchmark_pipeline_pct": round(100 * bench / n, 1),
        "perfect_parser_pct": round(100 * true / n, 1),
        "coax_pct": round(100 * coax / n, 1),
        "parser_effect_pts": round(100 * (true - bench) / n, 1),
        "prompt_effect_pts": round(100 * (coax - true) / n, 1),
        "total_pts": round(100 * (coax - bench) / n, 1),
        "_generator": "paper_analysis/none_showcase.py",
        "_source_csv": [FAITHFUL, COAX],
        "_generated_utc": datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds"),
    }
    os.makedirs(OUT_DIR, exist_ok=True)
    prov = (f"<!-- GENERATED by paper_analysis/none_showcase.py on {vals['_generated_utc']}. "
            f"Re-derived from committed raw outputs; run `python paper_analysis/none_showcase.py`. -->")
    table = "\n".join([
        prov,
        f"| GPT-4o on the {n} \"none of the above\" questions | Accuracy |",
        "|---|--:|",
        f"| Benchmark pipeline (its prompt, its parser) | {vals['benchmark_pipeline_pct']}% |",
        f"| Its prompt, but scored by the model's real answer | {vals['perfect_parser_pct']}% |",
        f"| Coax prompt (bare letter, benchmark parser) | {vals['coax_pct']}% |",
        "",
    ])
    with open(os.path.join(OUT_DIR, "none_showcase_table.md"), "w", encoding="utf-8") as f:
        f.write(table)
    with open(os.path.join(OUT_DIR, "none_showcase.values.json"), "w", encoding="utf-8") as f:
        json.dump(vals, f, indent=2)
    print(table)
    print(f"parser effect +{vals['parser_effect_pts']}, prompt effect +{vals['prompt_effect_pts']}, "
          f"total +{vals['total_pts']} (on {n} items)")


if __name__ == "__main__":
    main()
