"""
Find closed-ended items where two of the four options OVERLAP — one contains the other, or
they are near-duplicates — so more than one can be defended as correct.

Why it matters, and why it is worse than it first sounds. A question whose options include
both "#15" and "#15, and #16" does not have one right answer and three wrong ones: it has one
answer and one weaker version of the same answer. A model that correctly reads the X-ray and
identifies #15 can pick either, and only one is scored right. The score then measures which
phrasing the model happened to prefer, not whether it read the image.

This is a fingerprint of the generator described in §2: distractors were made by "randomly
perturbing" the correct answer, and a perturbation of a list is sometimes a sub-list, which is
still true.

Detection is deliberately conservative and mechanical — exact match, substring containment
after normalisation, or Jaccard token overlap >= 0.8. It will miss semantic overlaps that share
no words ("No" vs "Absent"), so the count here is a floor.

Run:  python -m paper_analysis.overlapping_options
"""
import datetime
import itertools
import json
import os
import re

import pandas as pd

OPTS = ["option1", "option2", "option3", "option4"]
JACCARD = 0.80


def norm(x):
    return " ".join(re.sub(r"[^a-z0-9 ]", " ", str(x).lower()).split())


def find(cl):
    rows = []
    for _, r in cl.iterrows():
        o = [norm(r[c]) for c in OPTS]
        if any(not x for x in o):
            continue
        for i, j in itertools.combinations(range(4), 2):
            a, b = o[i], o[j]
            ta, tb = set(a.split()), set(b.split())
            if not ta or not tb:
                continue
            jac = len(ta & tb) / len(ta | tb)
            kind = ("identical" if a == b else
                    "contains" if (a in b or b in a) else
                    "near-duplicate" if jac >= JACCARD else None)
            if kind:
                rows.append(dict(index=r["index"], kind=kind,
                                 opt_i="ABCD"[i], opt_j="ABCD"[j],
                                 text_i=r[OPTS[i]], text_j=r[OPTS[j]],
                                 key=str(r.answer).strip().upper(),
                                 key_in_pair=str(r.answer).strip().upper() in ("ABCD"[i], "ABCD"[j]),
                                 question=r.question))
                break
    return pd.DataFrame(rows)


def main():
    cl = pd.read_parquet("data/closed_ended.parquet")
    d = find(cl)
    os.makedirs("results/closed_ended", exist_ok=True)
    d.to_csv("results/closed_ended/overlapping_options.csv", index=False)

    n, N = len(d), len(cl)
    k = int(d.key_in_pair.sum())
    print(f"{n} of {N} closed items have two overlapping options ({100*n/N:.1f}%)")
    print(d.kind.value_counts().to_string())
    print(f"the answer key is one of the overlapping pair in {k}/{n}")

    out = os.path.join("paper_analysis", "_generated")
    os.makedirs(out, exist_ok=True)
    stamp = datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")
    lines = [f"<!-- GENERATED by paper_analysis/overlapping_options.py on {stamp}. "
             f"Do not hand-edit; run `python -m paper_analysis.overlapping_options`. -->",
             "| overlap | items | example pair |", "|:--|--:|:--|"]
    for kind in ("contains", "near-duplicate", "identical"):
        s = d[d.kind == kind]
        if not len(s):
            continue
        e = s.iloc[0]
        lines.append(f"| one option contains the other | {len(s)} | "
                     f"`{str(e.text_i)[:34]}` vs `{str(e.text_j)[:34]}` |"
                     if kind == "contains" else
                     f"| {kind} | {len(s)} | `{str(e.text_i)[:34]}` vs `{str(e.text_j)[:34]}` |")
    lines.append(f"| **total** | **{n}** | of which **{k}** have the key inside the pair |")
    frag = "\n".join(lines) + "\n"
    open(os.path.join(out, "overlapping_options_table.md"), "w", encoding="utf-8").write(frag)
    json.dump({"n_items": n, "n_closed": N, "key_in_pair": k,
               "by_kind": d.kind.value_counts().to_dict(),
               "_generator": "paper_analysis/overlapping_options.py", "_generated_utc": stamp},
              open(os.path.join(out, "overlapping_options.values.json"), "w"), indent=2)
    print("\n" + frag)


if __name__ == "__main__":
    main()
