"""
GENERATOR for: PAPER_DRAFT.md  §5.2  "The prompt alone moves the score" (table + stats)

Paired comparison of the benchmark's own prompt ("faithful") vs our engineered prompt
("coax") for GPT-4o on the CLEAN 453 questions (the working set fixed in §5.1). Same model,
same questions, same image settings (detail=high, temp=0); only the prompt wording changes.

  - faithful scores come from the committed E0-repro whole-491 run (faithful on a non-blank
    item is identical whether scored on the whole or the clean set) -> no extra API.
  - coax scores come from the committed coax whole-491 run.
Both are filtered to the 453 clean (answerable) items. Same items, two prompts -> McNemar.

Run:   python paper_analysis/prompt_axis.py
Reads: results/closed_ended/prompt_axis/gpt-4o-2024-11-20__coax-direct-k0__whole__n491.csv
       results/closed_ended/reproduction/gpt-4o-2024-11-20__faithful-direct-k0__whole__n491.csv
Writes: paper_analysis/_generated/prompt_axis_table.md   (the §5.2 clean table)
        paper_analysis/_generated/prompt_axis.values.json
"""
import os
import json
import math
import datetime
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
COAX_CSV = ("results/closed_ended/prompt_axis/"
            "gpt-4o-2024-11-20__coax-direct-k0__whole__n491.csv")
FAITHFUL_CSV = ("results/closed_ended/reproduction/"
                "gpt-4o-2024-11-20__faithful-direct-k0__whole__n491.csv")
OUT_DIR = os.path.join(HERE, "_generated")

BLANK_OPTION = {41, 50, 58, 73, 77, 87, 91, 105, 113, 114, 116, 125, 175, 188, 199, 205,
                230, 240, 288, 297, 327, 337, 391, 396, 435, 440, 444, 446, 455, 456, 477,
                486, 45, 48, 162, 204, 243, 325}  # all 38 blank-option items (§3.7)


def wilson(k, n, z=1.96):
    p = k / n
    den = 1 + z * z / n
    c = (p + z * z / (2 * n)) / den
    h = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / den
    return round(100 * (c - h), 1), round(100 * (c + h), 1)


def main():
    coax = pd.read_csv(os.path.join(REPO, *COAX_CSV.split("/")))
    repro = pd.read_csv(os.path.join(REPO, *FAITHFUL_CSV.split("/")))
    faith = (repro[["index", "correct"]].rename(columns={"correct": "faith"}))
    full = (coax[["index", "correct", "refused"]].rename(columns={"correct": "coax"})
            .merge(faith, on="index"))
    m = full[~full["index"].isin(BLANK_OPTION)]  # clean 453 (primary, for the §5.2 table)

    n = len(m)
    kf, kc = int(m["faith"].sum()), int(m["coax"].sum())
    fa, ca = round(100 * kf / n, 1), round(100 * kc / n, 1)
    fci, cci = wilson(kf, n), wilson(kc, n)
    b = int((~m["faith"] & m["coax"]).sum())   # faithful wrong, coax right
    c = int((m["faith"] & ~m["coax"]).sum())   # faithful right, coax wrong
    chi2 = (abs(b - c) - 1) ** 2 / (b + c) if (b + c) > 0 else 0.0
    p = math.erfc(math.sqrt(chi2 / 2)) if chi2 > 0 else 1.0

    # whole 491 too (robustness check: is the gain a clean-subset artifact?)
    nw = len(full)
    kfw, kcw = int(full["faith"].sum()), int(full["coax"].sum())
    faw, caw = round(100 * kfw / nw, 1), round(100 * kcw / nw, 1)
    bw = int((~full["faith"] & full["coax"]).sum())
    cw = int((full["faith"] & ~full["coax"]).sum())
    chiw = (abs(bw - cw) - 1) ** 2 / (bw + cw) if (bw + cw) > 0 else 0.0
    pw = math.erfc(math.sqrt(chiw / 2)) if chiw > 0 else 1.0

    vals = {
        "n_clean": n, "faithful_acc": fa, "faithful_ci": fci,
        "coax_acc": ca, "coax_ci": cci, "lift": round(ca - fa, 1),
        "coax_refusal_pct": round(m["refused"].mean() * 100, 1),
        "mcnemar_coax_right": b, "mcnemar_faithful_right": c,
        "mcnemar_chi2": round(chi2, 2), "mcnemar_p": p,
        "whole491": {"n": nw, "faithful_acc": faw, "coax_acc": caw,
                     "lift": round(caw - faw, 1), "mcnemar_coax_right": bw,
                     "mcnemar_faithful_right": cw, "mcnemar_chi2": round(chiw, 2),
                     "mcnemar_p": pw},
        "_generator": "paper_analysis/prompt_axis.py",
        "_source_csv": [COAX_CSV, FAITHFUL_CSV],
        "_generated_utc": datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds"),
    }
    os.makedirs(OUT_DIR, exist_ok=True)
    stamp = vals["_generated_utc"]
    prov = (f"<!-- GENERATED by paper_analysis/prompt_axis.py on {stamp}. "
            f"Do not hand-edit; run `python paper_analysis/prompt_axis.py`. -->")
    table = "\n".join([
        prov,
        "| Prompt | GPT-4o accuracy (clean, 453 questions) | 95% Wilson range |",
        "|---|---:|:--|",
        f"| Benchmark's own (\"faithful\") | {fa}% | {fci[0]} to {fci[1]} |",
        f"| Engineered (\"coax\") | {ca}% | {cci[0]} to {cci[1]} |",
        "",
    ])
    with open(os.path.join(OUT_DIR, "prompt_axis_table.md"), "w", encoding="utf-8") as f:
        f.write(table)
    with open(os.path.join(OUT_DIR, "prompt_axis.values.json"), "w", encoding="utf-8") as f:
        json.dump(vals, f, indent=2)

    print(table)
    print(f"clean 453: lift {vals['lift']:+} pts; McNemar coax-right={b}, faithful-right={c}, "
          f"chi2={chi2:.2f}, p={p:.2e}; coax refusals {vals['coax_refusal_pct']}%")
    print(f"whole 491: faithful {faw}% -> coax {caw}% (lift {caw-faw:+}); "
          f"McNemar chi2={chiw:.2f}, p={pw:.2e}")
    print(f"\nwrote {OUT_DIR}/prompt_axis_table.md and prompt_axis.values.json")


if __name__ == "__main__":
    main()
