"""
GENERATOR for: PAPER_DRAFT.md §7.4 — the question-quality audit readout.

Reads whatever quality-survey submissions have come back and reports, over every question
we recommend keeping:

  * how often the recorded answer is confirmed correct,
  * how often it is wrong,
  * how often a dentist looking at the actual radiograph cannot determine the answer.

That third number is the point. A question a clinician cannot settle with the image in
front of them does not have a determinable answer, so no model should be scored right or
wrong on it. It is a property of the question, not of any model.

Reports the same three splits by task type and by whether §7.2 had already flagged the
item, which tells us whether the mechanical flags predict the expert's verdicts.

Run:    python -m paper_analysis.quality_audit
Reads:  results/dentist_audit/quality_manifest.csv
        results/dentist_audit/quality_*_submission_*.json   (however many have returned)
Writes: paper_analysis/_generated/quality_audit_table.md, .values.json
"""
import datetime
import glob
import json
import os

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
OUT_DIR = os.path.join(HERE, "_generated")
VERDICTS = ["correct", "incorrect", "unsure"]
LABEL = {"correct": "recorded answer confirmed",
         "incorrect": "recorded answer wrong",
         "unsure": "cannot be determined from the radiograph"}


def p(*r):
    return os.path.join(REPO, *r)


def load():
    man = pd.read_csv(p("results/dentist_audit/quality_manifest.csv"), dtype={"image": str})
    subs = sorted(glob.glob(p("results/dentist_audit/quality_*_submission_*.json")))
    rows = []
    for f in subs:
        d = json.load(open(f, encoding="utf-8"))
        for r in d.get("responses", []):
            rows.append({"item_id": r["item_id"], "verdict": r.get("verdict"),
                         "comment": (r.get("comment") or "").strip(),
                         "rater": d.get("dentist_name") or d.get("token", "?"),
                         "batch": d.get("batch")})
    return man, pd.DataFrame(rows), subs


def main():
    man, ans, subs = load()
    if ans.empty:
        print("No quality-survey submissions found yet.")
        print(f"  expected at: results/dentist_audit/quality_<n>_submission_<token>.json")
        print(f"  manifest holds {len(man)} questions over {man.image.nunique()} images "
              f"in {man.survey.max()} surveys, so nothing is blocked; this reports as soon "
              f"as the first one returns.")
        return

    m = man.merge(ans, on="item_id", how="inner")
    n = len(m)
    counts = {v: int((m.verdict == v).sum()) for v in VERDICTS}
    stamp = datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")

    lines = [f"<!-- GENERATED by paper_analysis/quality_audit.py on {stamp}. "
             f"Do not hand-edit; run `python -m paper_analysis.quality_audit`. -->",
             f"| Dentist's verdict | questions | share |", "|:--|--:|--:|"]
    for v in VERDICTS:
        lines.append(f"| {LABEL[v]} | {counts[v]} | {100*counts[v]/n:.1f}% |")
    lines.append(f"| *reviewed so far* | {n} | of {len(man)} |")
    table = "\n".join(lines) + "\n"

    os.makedirs(OUT_DIR, exist_ok=True)
    open(os.path.join(OUT_DIR, "quality_audit_table.md"), "w", encoding="utf-8").write(table)
    vals = {"reviewed": n, "in_manifest": int(len(man)), "submissions": len(subs),
            "counts": counts, "share_pct": {v: round(100*counts[v]/n, 1) for v in VERDICTS},
            "by_task": {t: {v: int(((m.task_type == t) & (m.verdict == v)).sum()) for v in VERDICTS}
                        for t in sorted(m.task_type.unique())},
            "comments": int((m.comment != "").sum()),
            "_generator": "paper_analysis/quality_audit.py", "_generated_utc": stamp}
    json.dump(vals, open(os.path.join(OUT_DIR, "quality_audit.values.json"), "w"), indent=2)

    print(table)
    print(f"by task type:")
    for t, c in vals["by_task"].items():
        tot = sum(c.values())
        print(f"  {t:7s} n={tot:4d}  " + "  ".join(f"{v} {c[v]} ({100*c[v]/tot:.0f}%)" for v in VERDICTS))
    print(f"\ncomments left on {vals['comments']} of {n} reviewed questions")
    if counts["incorrect"] or counts["unsure"]:
        print("\nflagged items with a comment (the actionable ones):")
        for _, r in m[(m.verdict != "correct") & (m.comment != "")].head(12).iterrows():
            print(f"  [{r['index']}] {r.verdict:9s} {str(r.question)[:52]}")
            print(f"           \"{r.comment[:88]}\"")
    print(f"\nwrote {OUT_DIR}/quality_audit_table.md and .values.json")


if __name__ == "__main__":
    main()
