"""
GENERATOR for: PAPER_DRAFT.md §5.3.1 — what stripping the key costs GPT-4o.

GPT-4o under the revised (coax) prompt, scored on the same 491 questions once on the
benchmark's original (B-skewed) key and once on the position-balanced shuffled key. Both runs
use identical model-call settings (gpt-4o-2024-11-20, temperature 0, max_tokens 8192,
img_detail high, coax prompt); only the option order differs, so the accuracy drop isolates
how much of the score was resting on where the answer sat. The "guess-one-letter floor" is the
largest share any single letter holds in each key (always-B on the original, best letter on the
shuffled), i.e. what a model scores by ignoring the image and always picking one letter.

Run:   python paper_analysis/shuffle_drop.py
Reads: results/closed_ended/gpt-4o-...coax...whole__n491.csv          (original key)
       results/closed_ended/position_bias/gpt-4o-...coax...shuffled__n491.csv  (shuffled key)
Writes: paper_analysis/_generated/shuffle_drop_table.md + .values.json
"""
import os
import sys
import json
import math
import datetime
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
OUT_DIR = os.path.join(HERE, "_generated")
try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

ORIGINAL = "results/closed_ended/gpt-4o-2024-11-20__coax-direct-k0__whole__n491.csv"
SHUFFLED = "results/closed_ended/position_bias/gpt-4o-2024-11-20__coax-direct-k0__shuffled__n491.csv"


def wilson(k, n, z=1.96):
    p = k / n
    den = 1 + z * z / n
    c = (p + z * z / (2 * n)) / den
    h = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / den
    return round(100 * (c - h), 1), round(100 * (c + h), 1)


def summarize(df):
    k, n = int(df["correct"].sum()), len(df)
    lo, hi = wilson(k, n)
    floor = float(df["answer"].value_counts(normalize=True).max() * 100)
    return {"n": n, "acc": round(100 * k / n, 1), "ci": [lo, hi], "floor": round(floor, 1)}


def main():
    orig = pd.read_csv(os.path.join(REPO, *ORIGINAL.split("/")))
    shuf = pd.read_csv(os.path.join(REPO, *SHUFFLED.split("/")))
    assert set(orig["index"]) == set(shuf["index"]), "original and shuffled cover different items"

    o, s = summarize(orig), summarize(shuf)
    vals = {
        "n": o["n"],
        "original_key": o,
        "shuffled_key": s,
        "drop_pts": round(o["acc"] - s["acc"], 1),
        "floor_drop_pts": round(o["floor"] - s["floor"], 1),
        "_generator": "paper_analysis/shuffle_drop.py",
        "_source_csv": [ORIGINAL, SHUFFLED],
        "_generated_utc": datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds"),
    }
    os.makedirs(OUT_DIR, exist_ok=True)
    prov = (f"<!-- GENERATED by paper_analysis/shuffle_drop.py on {vals['_generated_utc']}. "
            f"Do not hand-edit; run `python paper_analysis/shuffle_drop.py`. -->")

    def row(label, d):
        return f"| {label} | {d['acc']}% [{d['ci'][0]}–{d['ci'][1]}] | {d['floor']}% |"

    table = "\n".join([
        prov,
        f"| GPT-4o, revised prompt ({o['n']} questions) | Accuracy [95% CI] | Guess-one-letter floor |",
        "|:--|--:|--:|",
        row("Original (B-skewed) key", o),
        row("Shuffled (balanced) key", s),
        "",
    ])
    with open(os.path.join(OUT_DIR, "shuffle_drop_table.md"), "w", encoding="utf-8") as f:
        f.write(table)
    with open(os.path.join(OUT_DIR, "shuffle_drop.values.json"), "w", encoding="utf-8") as f:
        json.dump(vals, f, indent=2)

    print(table)
    print(f"drop {vals['drop_pts']} pts (acc {o['acc']} -> {s['acc']}); "
          f"floor collapses {o['floor']} -> {s['floor']} ({vals['floor_drop_pts']} pts)")


if __name__ == "__main__":
    main()
