"""
Emit detector/MODEL_CARD.md straight from the checkpoints, so the training provenance of the
committed weights is a fact read off the files rather than something someone remembered.

Ultralytics stores the training arguments and the final validation metrics inside the .pt, so
every row below is extracted, not hand-written. Regenerate after replacing any weights:

  python detector/model_card.py
"""
import os

OUT = "detector/MODEL_CARD.md"
KEYS = ["model", "epochs", "imgsz", "batch", "mosaic", "optimizer", "lr0", "seed", "patience"]
NOTES = {
    "best.pt": (
        "v1. 32 output classes, one per FDI code, so one network both found teeth and named "
        "them. Behind every detector number in the paper before v0.33. **Kept unchanged** — "
        "replacing it would invalidate published figures."),
    "best2.pt": (
        "v2. **Single class** (`tooth`); numbering moved out of the network into "
        "`number_teeth.py`, which derives it from position. `single_cls` reads False because "
        "the dataset itself declares `nc: 1` (built by `prepare_data.py --single-class`) "
        "rather than the flag being set. This is the detector the paper's §8 uses."),
}


def main():
    import torch

    rows = []
    for w in ("best.pt", "best2.pt"):
        if not os.path.exists(w):
            continue
        ck = torch.load(w, map_location="cpu", weights_only=False)
        a = ck.get("train_args") or {}
        m = ck.get("train_metrics") or {}
        rows.append((w, ck, a, {k.split("(")[0].replace("metrics/", "").replace("val/", ""): v
                                for k, v in m.items() if isinstance(v, (int, float))}))

    L = ["# Detector weights — provenance",
         "",
         "<!-- GENERATED by detector/model_card.py from the checkpoints themselves.",
         "     Do not hand-edit; run `python detector/model_card.py`. -->",
         "",
         "Two detectors are committed. Both were trained on DENTEX set (b) via "
         "`detector/train.ipynb` on Colab, from the dataset `prepare_data.py` builds. Every "
         "field below is read out of the `.pt` file, not recalled.",
         ""]

    L += ["## Training run", "",
          "| | " + " | ".join(w for w, *_ in rows) + " |",
          "|---|" + "---|" * len(rows)]
    L.append("| trained (UTC) | " + " | ".join(str(ck.get("date", "?"))[:19] for _, ck, _, _ in rows) + " |")
    L.append("| ultralytics | " + " | ".join(str(ck.get("version", "?")) for _, ck, _, _ in rows) + " |")
    for k in KEYS:
        L.append(f"| {k} | " + " | ".join(str(a.get(k, "—")) for _, _, a, _ in rows) + " |")
    L.append("| dataset | " + " | ".join(str(a.get("data", "—")).split("/")[-2] for _, _, a, _ in rows) + " |")
    L.append("| size on disk | " + " | ".join(f"{os.path.getsize(w)/1e6:.1f} MB" for w, *_ in rows) + " |")

    L += ["", "## Validation metrics, held-out DENTEX split (61 images)", ""]
    L += ["| | " + " | ".join(w for w, *_ in rows) + " |", "|---|" + "---|" * len(rows)]
    for k in ("precision", "recall", "mAP50", "mAP50-95"):
        L.append(f"| {k} | " + " | ".join(f"{mt.get(k, float('nan')):.4f}" for *_, mt in rows) + " |")

    L += ["",
          "> **The mAP figures are not comparable between the two.** v1's is over 32 classes, "
          "so a correctly-placed box carrying the wrong FDI code counted against it; v2's is "
          "over one class and scores localisation only. Compare counting accuracy instead — "
          "see `detector/README.md` and `results/detector/inference_sweep*.csv`.",
          ""]

    L += ["## What each one is", ""]
    for w, *_ in rows:
        L.append(f"- **`{w}`** — {NOTES.get(w, '')}")

    L += ["",
          "## Reproducing",
          "",
          "The notebook is the runner and the repo is the source of truth: "
          "`detector/train.ipynb`, opened from GitHub, pulls this repo and calls the scripts "
          "below. Run it top to bottom on an L4.",
          "",
          "| stage | script |",
          "|---|---|",
          "| build the dataset | `prepare_data.py --out <dir> --single-class` |",
          "| train | `train.py --data <dir>/dentex.yaml --model yolov8s.pt --imgsz 1536 "
          "--batch 16 --epochs 150 --mosaic 0.0` |",
          "| validate | `validate.py --weights <best.pt> --data <dir>/dentex.yaml` |",
          "| tune inference | `tune_inference.py --weights best2.pt --res 1280,1536,1792 "
          "--iou 0.3,0.45,0.6,0.7` |",
          "| calibrate numbering | `calibrate_arch.py` |",
          "| score numbering | `eval_numbering.py --weights best2.pt --imgsz 1536 --conf 0.20 "
          "--iou 0.45 --method positional` |",
          "| router lift | `eval_router.py --weights best2.pt` |",
          "",
          "Training is **not** deterministic across machines even at a fixed seed (cuDNN "
          "kernel selection, GPU model). Re-running produces a *different* checkpoint, so "
          "replace committed weights only alongside re-running everything downstream of them.",
          "",
          "**Not in the repo:** the Colab run directories (`results.png`, `confusion_matrix.png`, "
          "`results.csv`, per-epoch logs) stay on Drive under "
          "`dentex_yolo_1cls/runs/dentex_v2_1cls/`. The checkpoints above carry the final "
          "metrics, which is what the paper cites; the curves are diagnostic only.",
          ""]

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(L))
    print(f"wrote {OUT} for {len(rows)} checkpoints")


if __name__ == "__main__":
    main()
